remote_theme: brianmaierjr/long-haul
title: Red Owl Games
description: What We Do

url: https://redowlgames.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Blog
    url: /blog.html

social:
  github: red-owl-games
  twitter: red_owl_games
  facebook: 
  email: support@redowlgames.com

google_analytics: 